### ISSUE TITLE
Bug: Cross-browser compatibility, UnsubscriptionError on Firefox

### ISSUE THREAD

**Issue by bgolyoo** [bleenco/ngx-uploader#300]
Not sure if you guys are aware of this bug or, if it's even a bug, but on your demo page ([http://ngx-uploader.com/](http://ngx-uploader.com/)) when viewed on firefox browser, if you try to upload a file there is an error on the concole that reads:
`ERROR Object { originalStack: "y@http://ngx-uploader.com/js/app.js…", zoneAwareStack: "y@http://ngx-uploader.com/js/app.js…", stack: "y@http://ngx-uploader.com/js/app.js…", message: "1 errors occurred during unsubscrip…", errors: Array[1], name: "UnsubscriptionError" }`

But Chrome doesn't seem to trhow this error message. 

This kind of UnsubscriptionError is present in our application as well. Does anybody have any inkling why is this error thrown and if it is a bug?

There is another a problem as well, and I'm not sure if it's connected to this in any way. But in my experience on Chrome you can't upload the same file twice. Basically when selecting the same file twice, it doesn't trigger anything. But on Firefox (becouse of the error?) you can select the same file after it has been selected, it triggers the same process as when you select a different file.

How could this behavior be prevented? Please advise!

**Comment by jkuri** [comment]
@bgolyoo I updated the demo. this was a bug in a library but was fixed in one of the last commits. can you please check again?

**Comment by bgolyoo** [comment]
Still getting the error on the demo page.

![ngx-uploader](https://user-images.githubusercontent.com/18516916/27835252-820724d8-60da-11e7-944c-be39e95e9958.png)

**Comment by ceras-ella** [comment]
Guys, any updates on this?

**Comment by retailify** [comment]
@ceras-ella could you please tell us, which Firefox release do you use?

**Comment by ceras-ella** [comment]
Updated to the latest version and the error is gone. Thanks!
I'm was using Firefox ESR v52.5.0. and ngx-uploader: 3.3.11. Do you happen to know in what version was this fixed?

**Comment by retailify** [comment]
@ceras-ella unfortunately not. I'm maintaining the project not long enough. I'm on board since 4.x.

it's maybe in release 3.0.2 [Changelog](https://github.com/bleenco/ngx-uploader/blob/master/CHANGELOG.md#302--2017-04-29)
